---

language: 'python'
python: '2.7'
sudo: True

virtualenv:
  system_site_packages: true

before_install: True
install: True

script:
  - 'git clone --depth 1 https://github.com/nickjj/rolespec'
  - 'cd rolespec ; bin/rolespec -r https://github.com/scibi/debops-test-suite'    
