---

- name: Manage Mosquitto server 
  hosts: [ 'debops_service_mosquitto' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:

    - role: debops.mosquitto/env
      tags: [ 'role::mosquitto', 'role::ferm', 'role::tcpwrappers' ]

    - role: debops.ferm
      tags: [ 'role::ferm' ]
      ferm__dependent_rules:
        - '{{ mosquitto__ferm__dependent_rules }}'

    - role: debops.tcpwrappers
      tags: [ 'role::tcpwrappers' ]
      tcpwrappers__dependent_allow:
        - '{{ mosquitto__tcpwrappers__dependent_allow }}'

    - role: debops.mosquitto
      tags: [ 'role::mosquitto' ]

